from .magic                import Magic
from .version              import Version
from .constant_pool        import *
from .access_flags         import AccessFlags
from .this_and_super_class import ThisAndSuperClass
from .interfaces           import Interfaces
from .fields               import Fields
from .methods              import Methods
from .attributes           import Attributes